version: '3'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:23.0.6
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HTTP_RELATIVE_PATH: /auth
      ports:
        - 8080:8080
      volumes: 
        - ./src/main/resources/theme/:/opt/keycloak/themes/
      entrypoint: /opt/keycloak/bin/kc.sh --verbose start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
